# termux-auto-forge termux.properties
# Terminal settings for Termux app
# Run `termux-reload-settings` after changes
# Wiki: https://wiki.termux.com/wiki/Terminal_Settings

###############
# General
###############

# allow-external-apps = true
# default-working-directory = /data/data/com.termux/files/home
# disable-terminal-session-change-toast = true
# hide-soft-keyboard-on-startup = true
# soft-keyboard-toggle-behaviour = enable/disable
# terminal-transcript-rows = 2000
# volume-keys = volume

###############
# Fullscreen mode
###############

# fullscreen = true
# use-fullscreen-workaround = true

###############
# Cursor
###############

# terminal-cursor-blink-rate = 0
# terminal-cursor-style = block

###############
# Extra keys
###############

# extra-keys-style = default
# extra-keys-text-all-caps = true

###############
# Colors/themes
###############

# use-black-ui = true

###############
# HW keyboard shortcuts
###############

# disable-hardware-keyboard-shortcuts = true
# shortcut.create-session = ctrl + t
# shortcut.next-session = ctrl + 2
# shortcut.previous-session = ctrl + 1
# shortcut.rename-session = ctrl + n

###############
# Bell key
###############

# bell-character = vibrate
bell-character = beep
# bell-character = ignore

###############
# Back key
###############

# back-key=escape
# back-key=back

###############
# Keyboard issue workarounds
###############

# enforce-char-based-input = true
# ctrl-space-workaround = true

###############
# Terminal Margin adjustments
###############

# terminal-margin-horizontal=3
# terminal-margin-vertical=0
